kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: app
  name: echo-server
  labels:
    app: echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: '25%'
      maxUnavailable: '25%'
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: main
        image: kimkimee2/node-http:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
